# TMUX config file ;)


# use zsh as default shell
#
set-option -g default-shell /bin/zsh


# start numbering at 1
#
set-option -g base-index 1
set-option -g pane-base-index 1


# enable true colors!
#
set-option -ga terminal-overrides ",xterm-256color:Tc"


# auto window renaming
# set-option -g allow-rename off


# window mathing current dir name
#
set -g window-status-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})#F'
set -g window-status-current-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})#F'
set-option -g status-interval 1


# vi key mode
#
setw -g mode-keys vi
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection


# hjkl pane traversal
#
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R


# bind <> for window swapping
#
bind-key -r < swap-window -t -
bind-key -r > swap-window -t +


# stay in current dir in new windows
#
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


# powerline plugin
source "$HOME/.powerline/powerline/bindings/tmux/powerline.conf"
