---
- name: Collecting facts
  hosts: localhost
  gather_facts: yes

- name: Set up local packages and configuration
  hosts: localhost
  roles:
  - neovim
  - zsh
  - tmux
  - X
  - {role: dwm, tags: ['gui']}
  - {role: st, tags: ['gui']}
