---
- name: Collecting facts
  hosts: localhost
  gather_facts: yes

- name: Set up local packages and configuration
  hosts: localhost
  roles:
  - neovim
  - zsh
  - tmux
  - {role: i3wm, tags: ['i3']}
  - {role: dwm, tags: ['dwm']}
  - {role: slock, tags: ['dwm']}
  - {role: X, tags: ['dwm', 'i3']}
  - st
