- name: Check if Xdefaults exists
  stat: path="~/.Xdefaults"
  register: xdefs_stat
  failed_when: False

- name: Backup Xdefaults
  command: mv ~/.Xdefaults ~/.Xdefaults.backup
  args:
    creates: "~/.Xdefaults.backup"
  when: xdefs_stat.stat.exists

- name: Create symbolic link for Xdefaults
  copy:
    src: "{{ playbook_dir }}/roles/X/files/Xdefaults"
    dest: "~/.Xdefaults"

- name: Check if Xresources exists
  stat: path="~/.Xresources"
  register: xress_stat
  failed_when: False

- name: Backup Xresources
  command: mv ~/.Xresources ~/.Xresources.backup
  args:
    creates: "~/.Xresources.backup"
  when: xress_stat.stat.exists

- name: Create symbolic link for Xresources
  copy:
    src: "{{ playbook_dir }}/roles/X/files/Xresources"
    dest: "~/.Xresources"
