" VIM classic settings
"{{{
  if &compatible
    set nocompatible
  endif

  filetype plugin indent on
  syntax enable

  " set leader key to space
  let mapleader=" "
  " set encoding
  set encoding=utf-8
  " set line numbering relative to cursor location
  set relativenumber
  " highlight current line
  set cursorline
  " change cusor type to horizontal line
  set guicursor+=n:hor20-Cursor/lCursor
  " disable backup files
  set nobackup
  " disable swap files
  set noswapfile
  " disable error bells
  set noerrorbells
  " confirm dialog before saving
  set confirm
  " number of visual spaces per TAB
  set tabstop=4
  " number of spaces in tab when editing
  set softtabstop=4
  " shifting value (<< & >>)
  set shiftwidth=4
  " tabs = spaces
  set expandtab
  " show white characters
  set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
"}}}

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
  if has('nvim')
    Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }
  else
    Plug 'Shougo/denite.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
  endif

  if has('nvim')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  else
    Plug 'Shougo/deoplete.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
  endif
  " {{{
    let g:deoplete#enable_at_startup = 1
  " }}}
  Plug 'dense-analysis/ale'
  Plug 'scrooloose/nerdtree'
  Plug 'tpope/vim-commentary'
  Plug 'majutsushi/tagbar'
  "{{{
    nmap <leader>tb :TagbarToggle<CR>
  "}}}
  Plug 'tpope/vim-fugitive'
  Plug 'airblade/vim-gitgutter'
  Plug 'sheerun/vim-polyglot'
  Plug 'morhetz/gruvbox'
  Plug 'Yggdroot/indentLine'
  "{{{
    let g:indent_guides_start_level = 2
    let g:indent_guides_guide_size = 1
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_auto_colors = 1
  "}}}
  Plug 'wakatime/vim-wakatime'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  " {{{
    nnoremap <silent> <leader><space> :Files<CR>
    nnoremap <silent> <leader>a :Buffers<CR>
    nnoremap <silent> <leader>A :Windows<CR>
    nnoremap <silent> <leader>; :BLines<CR>
    nnoremap <silent> <leader>o :BTags<CR>
    nnoremap <silent> <leader>O :Tags<CR>
    nnoremap <silent> <leader>? :History<CR>
  "}}}
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  "{{{
    let g:airline#extensions#ale#enabled = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_powerline_fonts = 1
  "}}}
call plug#end()

" Colors
"{{{
  if has("nvim")
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  
  if (has("termguicolors"))
    set termguicolors
  endif

  set t_Co=256
  set background=dark

  colorscheme gruvbox
"}}}

" Go
"{{{
 let g:go_fmt_command = "goimports"
 let g:go_highlight_functions = 1
 let g:go_highlight_methods = 1
 let g:go_highlight_fields = 1
 let g:go_highlight_types = 1
 let g:go_highlight_operators = 1
 let g:go_highlight_build_constraints = 1
 let g:go_def_mapping_enabled = 0
 let g:go_fmt_fail_silently = 1
 let g:go_term_enabled = 1
"}}}

" Wayland clipboard
"{{{
  xnoremap "+y y:call system("wl-copy", @")<cr>
  nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
  nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p
"}}}
