# Zsh and Git package installation
#
- name: Install zsh
  pacman: name=zsh state=latest
  become: True
  register: zsh_install

- name: Make sure zsh directory exists
  file: path="~/.config/zsh" state=directory

- name: Make sure zsh/themes directory exists
  file: path="~/.config/zsh/themes" state=directory

# Install oh-my-zsh ~ zsh management framework
#
- name: Clone oh-my-zsh
  git:
    repo=git://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: zsh_install|success

# Backup zshrc
#
- stat:
   path: ~/.zshrc
  register: zshrc_file

- name: Backup zshrc
  command: mv ~/.zshrc ~/.zshrc_backup
  args:
    creates: "~/.zshrc_packup"
  when: zshrc_file.stat.exists

- name: Create symbolic link for zshrc
  copy:
    src: "{{ playbook_dir }}/roles/zsh/files/zshrc"
    dest: "~/.zshrc"

- name: Copy extra zsh source files
  copy:
    src: "{{ playbook_dir }}/roles/zsh/files/{{ item }}"
    dest: "~/.config/zsh/{{ item }}"
  with_items:
  - "zsh_aliases"
  - "zsh_opts"

- name: Copy oh-my-zsh custom themes
  copy:
    src: "{{ playbook_dir }}/roles/zsh/files/themes/{{ item }}"
    dest: "~/.config/zsh/themes/{{ item }}"
  with_items:
  - "akamaru.zsh-theme"
