---
- name: Misc
  tags:
    - misc
  block:
    - name: Install tfenv
      git:
        repo: "https://github.com/tfutils/tfenv"
        dest: "~/.tfenv"

    - name: Install istioctlenv
      git:
        repo: "https://github.com/kirecek/istioctlenv"
        dest: "~/.istioctlenv"

    - name: Install plugin manager for tmux
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.tmux/plugins/tpm"

