---
- name: Install programming languages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - go
    - rust
    - elixir

- name: Add additional packages for python language
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pyenv

- name: Add virtualenv plugin for pyenv
  git:
    repo: "https://github.com/pyenv/pyenv-virtualenv"
    dest: "~/.pyenv/plugins/pyenv-virtualenv"
