---
- name: Sway
  tags:
    - sway
    - never
  block:
    - name: Install sway and related packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - sway
        - swaybg
        - swayidle
        - swaylock
        - waybar
        - mako
        - wofi
        - bemenu

    - name: Create sway/conf.d directory
      file:
        path: "~/.config/sway/config.d"
        state: directory
