---
- name: Common
  tags:
    - common
  block:
    - name: Install common packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - vim
        - neovim
        - openssh
        - gnupg
        - keybase
        - zsh
        - curl
        - wget
        - ntp
        - tmux
        - dialog
        - fzf
        - libnotify
        - bluez
        - inetutils
        - net-tools
        - traceroute
        - wireless_tools

    - name: Install alternative packages for default tools
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - bat
        - fd
        - ripgrep
        - exa

    - name: Install pluseaudio
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - pulseaudio
        - pulseaudio-bluetooth
        - pulseaudio-alsa
        - pavucontrol
      tags:
        - pulseaudio
        - audio

    - name: Install icons
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - adwaita-icon-theme

    - name: Install fonts
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - ttf-hack
        - ttf-fira-code
        - ttf-fira-mono
        - ttf-font-awesome
        - ttf-inconsolata
        - ttf-opensans
        - ttf-dejavu
        - ttf-droid
        - ttf-ubuntu-font-family
        - awesome-terminal-fonts
