---
- name: Common
  tags:
    - common
  block:
    - name: Install common packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - vim
        - neovim
        - openssh
        - gnupg
        - keybase
        - zsh
        - curl
        - ntp
        - tmux
        - dialog
        - bat
        - fd
        - ripgrep
        - fzf
        - libnotify
        - bluez

    - name: Install pluseaudio
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - pulseaudio
        - pulseaudio-bluetooth
        - pulseaudio-alsa
      tags:
        - pulseaudio
        - audio

    - name: Install tfenv
      git:
        repo: "https://github.com/tfutils/tfenv"
        dest: "~/.tfenv"

    - name: Install plugin manager for tmux
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.tmux/plugins/tpm"

    - name: Install icons
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - adwaita-icon-theme

    - name: Install fonts
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - ttf-hack
        - ttf-fira-code
        - ttf-fira-mono
        - ttf-font-awesome
        - ttf-inconsolata
        - ttf-opensans
        - ttf-dejavu
        - ttf-droid
        - ttf-ubuntu-font-family
        - awesome-terminal-fonts
