---
- name: Wayland
  tags:
    - wayland
    - sway
    - never
  block:
    - name: Install common wayland packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - wayland
        - wayland-protocols
        - wlroots
        - wl-clipboard
        - xorg-server-xwayland
