---
- name: Wayland common
  tags:
    - sway
    - wayland
    - never
  block:
    - name: Install common wayland packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - mako
        - wofi
        - bemenu
        - grim
        - slurp
        - light

- name: Sway
  tags:
    - sway
    - never
  block:
    - name: Install sway and related packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - sway
        - swaybg
        - swayidle
        - swaylock
        - waybar

    - name: Create sway/conf.d directory
      file:
        path: "~/.config/sway/config.d"
        state: directory
