---
- name: X common
  tags:
    - xorg
    - never
  block:
    - name: Install common X packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - xorg-server
        - xorg-apps
        - xorg-xinit
        - xorg-xsetroot
        - xcape
        - rofi
        - dmenu
        - dunst
        - clipmenu
        - slock
