# i3status configuration file.
# see "man i3status" for documentation.

general {
  colors = false
  interval = 1
}

order += "disk /"
order += "wireless wlp3s0"
order += "volume master"
order += "battery 0"
order += "battery 1"
order += "tztime local"

disk "/" {
        format = "  %free "
}

wireless wlp3s0 {
        format_up = "   (%essid) %ip "
        format_down = "   down "
}

battery 0 {
        format = "⚡ %status %percentage "
}

battery 1 {
        format = "⚡ %status %percentage "
}

tztime local {
        format = "  %Y-%m-%d %H:%M:%S "
}

volume master {
        format = " ♪ %volume "
        format_muted = "♪: muted (%volume)"
        device = "pulse"
}
