# Tmux package installation
#
- name: Install latest tmux package
  pacman: name=tmux state=latest
  become: True

# Backup existing configuration
#
- name: Check if .tmux.conf exists
  stat: path="~/.tmux.conf"
  register: tmux_stat

- name: Backup existing tmux configuration
  command: mv ~/.tmux.conf ~/.tmux_backup.conf
  args:
    creates: "~/.tmux.conf"
  when: tmux_stat.stat.exists

# Postinstall configuration
#
- name: Create symbolic link for tmux conf file
  copy:
    src: "{{ playbook_dir }}/roles/tmux/files/tmux.conf"
    dest: "~/.tmux.conf"
