# vim: set syntax=toml:

[admiral]
items = [
    "left", "workspaces",
    "center", "clock",
    "right", "clock"
]

# ---------- plugins
[workspaces]
path = "./plugins/workspaces.py"

[clock]
path = "./plugins/clock"

# ---------- lemonbar format settings
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true
