# Neovim package installation
#
- name: Install latest neovim package
  pacman: name=neovim state=latest
  become: True

# Prepare python virtualenv
#
- name: Install neopy3 virtualenvironment
  pip:
    virtualenv: "~/.virtualenvs/neopy3"
    virtualenv_python: python3
    name: neovim

- name: Install neopy2 virtualenvironment
  pip:
    virtualenv: "~/.virtualenvs/neopy2"
    virtualenv_python: python2
    name: neovim

# Plugin management for neovim
#
- name: Makes sure autoload directory exists
  file: path="~/.config/nvim/autoload" state=directory

- name: Makes sure plugged directory exists
  file: path="~/.plugged" state=directory

- name: Install vim-plug for neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.config/nvim/autoload/plug.vim"

# Postinstall configuration
#
- name: Check if init.vim exists
  stat: path="~/.config/nvim/init.vim"
  register: neoinit_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.config/nvim/init.vim ~/.config/nvim/init.vim.backup
  args:
    creates: "~/config/nvim/init.vim.backup"
  when: neoinit_stat.stat.exists

- name: Create init.vim config file
  copy:
    src: "{{ playbook_dir }}/roles/neovim/files/init.vim"
    dest: "~/.config/nvim/init.vim"

# TODO
# - name: Install Plug modules
#   command: nvim +PlugInstall +qall
